import Link from 'next/link';
import { Button, PageHero, SectionHeader } from '@/components/ui/Primitives';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';

const offerings = [
  ['Intelligent Systems', 'Agents, workflows and decision support shaped around the way a company actually operates.', '/products/intelligent-systems'],
  ['Intelligence Infrastructure', 'The knowledge, data, evaluation and orchestration layers that make intelligence reliable.', '/products/intelligence-infrastructure'],
  ['Custom Models', 'Research-led custom work for specialized problems where off-the-shelf capability is insufficient.', '/products/custom-models'],
  ['Custom Infrastructure', 'The systems beneath the system: services, architecture and foundations built to evolve.', '/products/custom-infrastructure'],
  ['AI R&D', 'Experimental work for opportunities that have no standard answer yet.', '/products/ai-rd'],
  ['Consulting & Advisory', 'Technical judgment that turns an unclear opportunity into a useful next decision.', '/products/consulting-advisory'],
];

export function ProductsExperience() { return <>
  <PageHero kicker="Products" title={<>Intelligence, built as a <em>system.</em></>} copy="We build AI systems across the layers that actually make intelligence useful—from agents and workflows to knowledge infrastructure, custom models, infrastructure and research. Not every problem needs every layer. We determine what the problem requires, then build accordingly."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Discuss your system</Button><Button href="/docs/solutions" variant="secondary">Explore the technical layer</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What Genjecx builds" title={<>Not a catalogue of features. A set of <em>capabilities that work together.</em></>} copy="Each engagement is a different entry point into the same long-term goal: useful intelligence that compounds with your company."/><div className="gx-offering-grid">{offerings.map(([title,copy,href],index)=><Link key={title} href={href} className="gx-offering"><span>0{index + 1}</span><h2 className="gx-display">{title}</h2><p>{copy}</p><b>Learn how it works →</b></Link>)}</div></div></section>
  <section className="gx-section gx-process-band"><div className="gx-container"><SectionHeader kicker="How it comes together" title={<>Start with the problem. Build the <em>right layer.</em></>} align="center"/><div className="gx-marketing-flow">{['Context','Architecture','System','Learning'].map((step,index)=><div key={step}><span>0{index + 1}</span><strong>{step}</strong>{index < 3 && <b>→</b>}</div>)}</div><p>Some companies need a clear architecture first. Others need an intelligent workflow, a knowledge layer or deeper R&D. The work begins at the point of greatest leverage.</p></div></section>
  <section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Designed to compound</div><h2 className="gx-display">A system should become <em>more useful</em> as it learns.</h2></div><div className="gx-copy"><p>Genjecx considers what the system needs now, what information it will accumulate and how future improvement becomes easier—not simply what can be demoed this month.</p><Button href="/docs/research" variant="secondary">Explore research & development</Button></div></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">A useful next step</div><h2 className="gx-display">Not sure where to begin?</h2><p>Start with a conversation about the system beneath the idea.</p><Button href="/ArchitectureAudit">Request an architecture audit</Button></div></section>
</>; }

const integrationCategories = [
  ['Cloud Infrastructure', 'Existing cloud environments, compute, storage, networking, deployment and security boundaries.'],
  ['Data & Knowledge', 'Databases, warehouses, documents, internal knowledge, event streams and structured data.'],
  ['AI Model Services', 'Hosted models, local models, specialized models and model-routing architectures.'],
  ['Business Systems', 'CRMs, internal applications, operational software, SaaS platforms and enterprise systems.'],
  ['APIs & Services', 'External APIs and internal services that intelligence needs to interact with.'],
  ['Observability', 'Logs, metrics, traces, evaluation systems and operational monitoring.'],
  ['Human Systems', 'Approval workflows, human review, decision points and feedback loops.'],
];
const integrationProcess = [['Map', 'Understand the existing technical environment.'], ['Connect', 'Identify the data, APIs, systems and workflows intelligence needs access to.'], ['Route', 'Determine how information moves between models, tools, services and users.'], ['Secure', 'Define access boundaries, data handling, permissions and operational constraints.'], ['Evaluate', 'Measure whether the integrated system actually performs better.'], ['Operate', 'Monitor cost, reliability, latency, failures and system behavior over time.']];
const scenarios = [['Existing Product + New AI Layer', 'Add intelligence without rebuilding the product.'], ['Multiple Data Sources + Intelligence System', 'Bring fragmented organizational knowledge into one usable intelligence layer.'], ['Existing AI Stack + Architecture Problems', 'Rework routing, retrieval, evaluation, memory or infrastructure.'], ['Enterprise Systems + AI Agents', 'Allow agents to work with existing business systems under controlled permissions.'], ['Custom Model + Production Infrastructure', 'Deploy specialized models into an operational environment.'], ['Research Prototype + Production System', 'Turn an experimental architecture into something that can actually operate.']];
export function IntegrationsExperience() { return <>
  <PageHero kicker="Integrations" title={<>Intelligence doesn&apos;t <em>live alone.</em></>} copy="GenJecX systems are designed to become part of the technology environment a company already relies on. We don&apos;t treat AI as another disconnected destination. We connect intelligence to the data, infrastructure, applications, workflows and people already operating the business."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Start a Conversation →</Button><Button href="/docs/work/architecture" variant="secondary">Explore Architecture</Button></div></PageHero>
  <section className="gx-section gx-integration-model"><div className="gx-container"><SectionHeader kicker="The integration model" title={<>Intelligence is part of the <em>environment.</em></>} copy="A system relationship map—not a logo wall."/><div className="gx-integration-map" role="img" aria-label="Users connect to an intelligence layer of agents, models, decisions and apps. The intelligence layer connects with data, business systems and tools, which rest on infrastructure."><div className="gx-im-node users">Users</div><div className="gx-im-node intelligence"><strong>GenJecX Intelligence Layer</strong><small>Agents / Models / Decisions / Apps</small></div><div className="gx-im-branches"><article><b>Data</b><span>Databases · Documents · Knowledge</span></article><article><b>Business Systems</b><span>CRM / ERP · SaaS · Internal Apps</span></article><article><b>Tools</b><span>APIs · Services · External APIs</span></article></div><div className="gx-im-node infrastructure"><strong>Infrastructure</strong><small>Cloud / Compute · Storage / APIs</small></div></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What we integrate with" title={<>Seven parts of the <em>real environment.</em></>} /><div className="gx-integration-cards">{integrationCategories.map(([title,copy], index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Build around what already exists</div><h2 className="gx-display">Your stack does not need to be replaced to become <em>more intelligent.</em></h2></div><div className="gx-copy"><p>Sometimes the right architecture introduces a new intelligence layer. Sometimes an existing component needs replacing. Sometimes nothing changes except how information flows between systems. We determine that from the architecture—not a predetermined integration checklist.</p></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Integration process" title={<>Map the system before asking it to <em>work together.</em></>} /><div className="gx-lifecycle">{integrationProcess.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section gx-integration-deep"><div className="gx-container"><SectionHeader kicker="Integration is not just API connectivity" title={<>A connected system is not necessarily an <em>integrated system.</em></>} copy="An API can connect two services. Architecture determines whether they work together."/><FlowDiagram label="Architecture underneath integration" steps={['Data', 'Knowledge', 'Models', 'Applications', 'Infrastructure', 'Users', 'Evaluation']} /><div className="gx-scope-list">{['Where context comes from and how knowledge is retrieved', 'Which model receives information and what tools it can use', 'Where decisions happen and what gets remembered', 'What gets evaluated and what happens when something fails'].map((item,index)=><div key={item}><span>0{index+1}</span>{item}</div>)}</div><div className="gx-page-actions"><Button href="/docs/work/architecture" variant="secondary">Explore the Architecture →</Button></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Common integration scenarios" title={<>Integration where architecture meets <em>reality.</em></>} /><div className="gx-offering-grid">{scenarios.map(([title,copy],index)=><article className="gx-offering" key={title}><span>0{index+1}</span><h2 className="gx-display">{title}</h2><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Already have a stack?</div><h2 className="gx-display">Good. We do not need you to start over.</h2><p>Show us what exists, what needs to connect and what is not working. We&apos;ll help determine where intelligence belongs.</p><Button href="/ArchitectureAudit">Talk Through Your Ecosystem →</Button></div></section>
</>; }

const engagementDepths = [
  { title:'Quick AI Solutions', subtitle:'Focused Intelligence for Bounded Problems', usd:'$600–$2,400+', inr:'₹50K–₹2L+', timeline:'3–7 days', copy:'For teams with a clearly defined problem that needs a focused AI capability without becoming a large systems project.', builds:['AI applications','AI assistants','Focused agents','Workflow automation','RAG systems','AI copilots','API integrations','Prompt/context engineering','Small multi-agent systems','AI-powered internal tools'], engineering:'$95–$240 / month', engineeringInr:'₹8K–₹20K / month', infrastructure:'$35–$120 / month', infrastructureInr:'₹3K–₹10K / month', includes:['AI application','Agents & assistants','Workflow intelligence','RAG & knowledge retrieval','Model & API integration','Evaluation','Deployment'], note:'Infrastructure costs depend on actual usage and deployment requirements.' },
  { title:'Custom AI Integration / Intelligence Systems', subtitle:'When AI Becomes Part of the System', usd:'$2,400–$7,200+', inr:'₹2L–₹6L+', timeline:'1–2+ weeks', copy:'For companies where AI needs to become a deeper architectural layer rather than simply another feature. Complex systems may require longer depending on scope.', builds:['Intelligence systems','Personal intelligence systems','Knowledge systems','Persistent-memory applications','Multi-agent architectures','Complex RAG systems','Enterprise AI workflows','AI operating systems','Deep product integrations'], engineering:'$240–$720 / month', engineeringInr:'₹20K–₹60K / month', infrastructure:'$120–$360 / month', infrastructureInr:'₹10K–₹30K / month', includes:['Custom dataset engineering','Intelligence layer','Persistent memory','Knowledge graphs','Advanced orchestration','Evaluation pipelines','Production integration'], note:'Actual infrastructure requirements are determined by system architecture and usage.' },
  { title:'Custom Neural R&D / Enterprise', subtitle:'When Generic AI Isn’t Enough', usd:'$7,200–$24,000+', inr:'₹6L–₹20L+', timeline:'Custom-scoped', copy:'For technically demanding problems where existing models or conventional architectures are not sufficient. This is where GenJecX moves from AI integration into AI R&D.', builds:['Custom neural models','Specialized model architectures','Custom training','Neural architecture research','Deterministic inference','Model optimization','Neuro-symbolic systems','Enterprise intelligence infrastructure','Research-led AI products'], engineering:'$720–$2,400 / month', engineeringInr:'₹60K–₹2L / month', infrastructure:'$360–$1,200+ / month', infrastructureInr:'₹30K–₹1L+ / month', includes:['Custom neural architectures','Custom training','Specialized inference','Neural architecture research','Model optimization','Neuro-symbolic systems','Enterprise deployment'], note:'Infrastructure pricing depends heavily on compute requirements and usage.' },
];
export function PricingExperience() { const factors = [['Problem Complexity','How difficult is the underlying problem?'],['Intelligence Depth','Generation, retrieval, agents, memory, decisions or specialized models.'],['Data Complexity','Data engineering and knowledge structuring required.'],['Integration Depth','Connection to products, data, APIs and infrastructure.'],['Evaluation Requirements','How rigorously the system needs to be tested.'],['Infrastructure','Compute, storage, deployment, monitoring and operations.'],['Research','Whether an established approach exists or experimentation is required.']]; return <>
  <PageHero kicker="Pricing" title={<>Build at the depth the <em>problem requires.</em></>} copy="Not every AI problem needs a custom model. Not every workflow needs an agent. And not every system needs to be rebuilt from scratch. GenJecX engagements are scoped around the complexity of the problem, depth of intelligence, engineering required and infrastructure needed to make the system useful in the real world."><p className="gx-pricing-thesis">The problem determines the architecture. The architecture determines the engagement.</p><div className="gx-page-actions"><Button href="/ArchitectureAudit">Start a Conversation →</Button><Button href="/docs/work/architecture" variant="secondary">Explore Architecture</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Build → Optional Ongoing Engineering → Optional Managed Infrastructure" title={<>Three build depths. No <em>SaaS packages.</em></>} copy="Build is the one-time engineering engagement. Ongoing engineering and managed infrastructure are optional and only apply when the system requires them."/><div className="gx-pricing-architecture">{engagementDepths.map((tier,index)=><article key={tier.title}><span>TIER 0{index+1}</span><h2 className="gx-display">{tier.title}</h2><h3>{tier.subtitle}</h3><strong>{tier.usd}</strong><small>{tier.inr}</small><b>BUILD</b><p>{tier.copy}</p><em>Typical build timeline: {tier.timeline}</em><div className="gx-pricing-columns"><div><h4>Typical builds</h4><ul>{tier.builds.map(item=><li key={item}>{item}</li>)}</ul></div><div><h4>What the build can include</h4><ul>{tier.includes.map(item=><li key={item}>{item}</li>)}</ul></div></div><div className="gx-recurring-grid"><div><span>OPTIONAL / ONGOING ENGINEERING</span><strong>{tier.engineering}</strong><small>{tier.engineeringInr}</small><p>Maintenance, evaluation, optimization and continued system development.</p></div><div><span>OPTIONAL / MANAGED INFRASTRUCTURE</span><strong>{tier.infrastructure}</strong><small>{tier.infrastructureInr}</small><p>Only when GenJecX manages hosting and operational infrastructure.</p></div></div><p className="gx-pricing-note">{tier.note}</p><Link href="/ArchitectureAudit">Discuss this build →</Link></article>)}</div><p className="gx-currency-note">USD figures are indicative conversions. Final pricing is quoted in the agreed billing currency.</p></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="Three different things. One system." title={<>Choose only what the system <em>actually needs.</em></>} /><div className="gx-commercial-model">{[['Build','The initial engineering required to create the system. One-time project engagement.'],['Ongoing Engineering','Continued improvement, maintenance, evaluation, optimization and development. Optional monthly engagement.'],['Managed Infrastructure','Hosting and operation of the system. Only applicable when GenJecX manages it.']].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div><p className="gx-pricing-callout">You don’t automatically pay all three. The engagement may be Build only; Build + Engineering; Build + Infrastructure; or Build + Engineering + Infrastructure.</p></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What determines the price?" title={<>Engineering depth, not a <em>feature checklist.</em></>} /><div className="gx-pricing-factors">{factors.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section gx-audit-pricing"><div className="gx-container gx-two-column"><div><div className="gx-kicker">AI Architecture Audit</div><h2 className="gx-display">Technical judgment before the <em>next build.</em></h2></div><div className="gx-copy"><p>Already have an AI system, are planning one, or have tried several approaches? We examine architecture, data flow, model usage, retrieval, infrastructure, failure modes, evaluation, cost efficiency and operational risks.</p><p>You receive an audit report, system diagrams, risk cards, assessments and prioritized recommendations.</p><blockquote>We don&apos;t audit to find reasons to rebuild. Sometimes the answer is to keep the system. Sometimes one layer needs to change. Sometimes the right answer is to stop building.</blockquote><Button href="/docs/work/architecture-audits">Request an Architecture Audit →</Button></div></div></section>
  <section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Consulting & Advisory</div><h2 className="gx-display">Technical judgment before the commitment to <em>build.</em></h2></div><div className="gx-copy"><p>Not every problem needs a build engagement. Advisory can establish technical strategy, architecture decisions, build-vs-buy-vs-integrate judgment, existing-system diagnosis and AI product direction before engineering resources are committed.</p><Button href="/products/consulting-advisory" variant="secondary">Explore Consulting & Advisory</Button></div></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Not sure which tier?</div><h2 className="gx-display">You don&apos;t need to know <em>yet.</em></h2><p>Tell us what you are trying to build, the problem you are solving, what you have already tried and what success looks like. We&apos;ll determine the appropriate architectural depth.</p><Button href="/ArchitectureAudit">Start a Conversation →</Button></div></section>
</>; }

export function ResourceLanding({ type }: { type: 'templates' | 'blogs' }) { const isTemplates = type === 'templates'; return <>
  <PageHero kicker={isTemplates ? 'Templates' : 'Blogs'} title={isTemplates ? <>Practical starting points for <em>intelligent systems.</em></> : <>Ideas, research and engineering <em>in progress.</em></>} copy={isTemplates ? 'Reusable knowledge will live here as Genjecx publishes approved system blueprints, workflow patterns and R&D frameworks.' : 'A home for approved Genjecx thinking across systems, engineering, research and company work.'}><div className="gx-page-actions"><Button href="/ArchitectureAudit">Start a conversation</Button><Button href="/docs" variant="secondary">Explore Docs</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container gx-resource-note"><div className="gx-kicker">Growing resource library</div><h2 className="gx-display">{isTemplates ? 'No manufactured marketplace.' : 'No manufactured editorial calendar.'}</h2><p>{isTemplates ? 'There are no verified production templates in the current repository, so this page intentionally provides a focused resource destination rather than inventing downloadable assets.' : 'There are no verified production articles in the current repository, so this page intentionally provides a focused editorial destination rather than inventing authors, dates or claims.'}</p><div><Link href="/docs/research">Research & Development →</Link><Link href="/docs/work">Explore the work →</Link><Link href="/docs/solutions">What Genjecx builds →</Link></div></div></section>
</>; }
