import Link from 'next/link';
import { Button, PageHero, SectionHeader } from '@/components/ui/Primitives';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';

const offerings = [
  ['Intelligent Systems', 'Agents, workflows and decision support shaped around the way a company actually operates.', '/products/intelligent-systems'],
  ['Intelligence Infrastructure', 'The knowledge, data, evaluation and orchestration layers that make intelligence reliable.', '/products/intelligence-infrastructure'],
  ['Custom Models', 'Research-led custom work for specialized problems where off-the-shelf capability is insufficient.', '/products/custom-models'],
  ['Custom Infrastructure', 'The systems beneath the system: services, architecture and foundations built to evolve.', '/products/custom-infrastructure'],
  ['AI R&D', 'Experimental work for opportunities that have no standard answer yet.', '/products/ai-rd'],
  ['Consulting & Advisory', 'Technical judgment that turns an unclear opportunity into a useful next decision.', '/products/consulting-advisory'],
];

export function ProductsExperience() { return <>
  <PageHero kicker="Products" title={<>Intelligence, built as a <em>system.</em></>} copy="We build AI systems across the layers that actually make intelligence useful—from agents and workflows to knowledge infrastructure, custom models, infrastructure and research. Not every problem needs every layer. We determine what the problem requires, then build accordingly."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Discuss your system</Button><Button href="/docs/solutions" variant="secondary">Explore the technical layer</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What Genjecx builds" title={<>Not a catalogue of features. A set of <em>capabilities that work together.</em></>} copy="Each engagement is a different entry point into the same long-term goal: useful intelligence that compounds with your company."/><div className="gx-offering-grid">{offerings.map(([title,copy,href],index)=><Link key={title} href={href} className="gx-offering"><span>0{index + 1}</span><h2 className="gx-display">{title}</h2><p>{copy}</p><b>Learn how it works →</b></Link>)}</div></div></section>
  <section className="gx-section gx-process-band"><div className="gx-container"><SectionHeader kicker="How it comes together" title={<>Start with the problem. Build the <em>right layer.</em></>} align="center"/><div className="gx-marketing-flow">{['Context','Architecture','System','Learning'].map((step,index)=><div key={step}><span>0{index + 1}</span><strong>{step}</strong>{index < 3 && <b>→</b>}</div>)}</div><p>Some companies need a clear architecture first. Others need an intelligent workflow, a knowledge layer or deeper R&D. The work begins at the point of greatest leverage.</p></div></section>
  <section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Designed to compound</div><h2 className="gx-display">A system should become <em>more useful</em> as it learns.</h2></div><div className="gx-copy"><p>Genjecx considers what the system needs now, what information it will accumulate and how future improvement becomes easier—not simply what can be demoed this month.</p><Button href="/docs/research" variant="secondary">Explore research & development</Button></div></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">A useful next step</div><h2 className="gx-display">Not sure where to begin?</h2><p>Start with a conversation about the system beneath the idea.</p><Button href="/ArchitectureAudit">Request an architecture audit</Button></div></section>
</>; }

const integrationCategories = [
  ['Cloud Infrastructure', 'Existing cloud environments, compute, storage, networking, deployment and security boundaries.'],
  ['Data & Knowledge', 'Databases, warehouses, documents, internal knowledge, event streams and structured data.'],
  ['AI Model Services', 'Hosted models, local models, specialized models and model-routing architectures.'],
  ['Business Systems', 'CRMs, internal applications, operational software, SaaS platforms and enterprise systems.'],
  ['APIs & Services', 'External APIs and internal services that intelligence needs to interact with.'],
  ['Observability', 'Logs, metrics, traces, evaluation systems and operational monitoring.'],
  ['Human Systems', 'Approval workflows, human review, decision points and feedback loops.'],
];
const integrationProcess = [['Map', 'Understand the existing technical environment.'], ['Connect', 'Identify the data, APIs, systems and workflows intelligence needs access to.'], ['Route', 'Determine how information moves between models, tools, services and users.'], ['Secure', 'Define access boundaries, data handling, permissions and operational constraints.'], ['Evaluate', 'Measure whether the integrated system actually performs better.'], ['Operate', 'Monitor cost, reliability, latency, failures and system behavior over time.']];
const scenarios = [['Existing Product + New AI Layer', 'Add intelligence without rebuilding the product.'], ['Multiple Data Sources + Intelligence System', 'Bring fragmented organizational knowledge into one usable intelligence layer.'], ['Existing AI Stack + Architecture Problems', 'Rework routing, retrieval, evaluation, memory or infrastructure.'], ['Enterprise Systems + AI Agents', 'Allow agents to work with existing business systems under controlled permissions.'], ['Custom Model + Production Infrastructure', 'Deploy specialized models into an operational environment.'], ['Research Prototype + Production System', 'Turn an experimental architecture into something that can actually operate.']];
export function IntegrationsExperience() { return <>
  <PageHero kicker="Integrations" title={<>Intelligence doesn&apos;t <em>live alone.</em></>} copy="GenJecX systems are designed to become part of the technology environment a company already relies on. We don&apos;t treat AI as another disconnected destination. We connect intelligence to the data, infrastructure, applications, workflows and people already operating the business."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Start a Conversation →</Button><Button href="/docs/work/architecture" variant="secondary">Explore Architecture</Button></div></PageHero>
  <section className="gx-section gx-integration-model"><div className="gx-container"><SectionHeader kicker="The integration model" title={<>Intelligence is part of the <em>environment.</em></>} copy="A system relationship map—not a logo wall."/><div className="gx-integration-map" role="img" aria-label="Users connect to an intelligence layer of agents, models, decisions and apps. The intelligence layer connects with data, business systems and tools, which rest on infrastructure."><div className="gx-im-node users">Users</div><div className="gx-im-node intelligence"><strong>GenJecX Intelligence Layer</strong><small>Agents / Models / Decisions / Apps</small></div><div className="gx-im-branches"><article><b>Data</b><span>Databases · Documents · Knowledge</span></article><article><b>Business Systems</b><span>CRM / ERP · SaaS · Internal Apps</span></article><article><b>Tools</b><span>APIs · Services · External APIs</span></article></div><div className="gx-im-node infrastructure"><strong>Infrastructure</strong><small>Cloud / Compute · Storage / APIs</small></div></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What we integrate with" title={<>Seven parts of the <em>real environment.</em></>} /><div className="gx-integration-cards">{integrationCategories.map(([title,copy], index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Build around what already exists</div><h2 className="gx-display">Your stack does not need to be replaced to become <em>more intelligent.</em></h2></div><div className="gx-copy"><p>Sometimes the right architecture introduces a new intelligence layer. Sometimes an existing component needs replacing. Sometimes nothing changes except how information flows between systems. We determine that from the architecture—not a predetermined integration checklist.</p></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Integration process" title={<>Map the system before asking it to <em>work together.</em></>} /><div className="gx-lifecycle">{integrationProcess.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section gx-integration-deep"><div className="gx-container"><SectionHeader kicker="Integration is not just API connectivity" title={<>A connected system is not necessarily an <em>integrated system.</em></>} copy="An API can connect two services. Architecture determines whether they work together."/><FlowDiagram label="Architecture underneath integration" steps={['Data', 'Knowledge', 'Models', 'Applications', 'Infrastructure', 'Users', 'Evaluation']} /><div className="gx-scope-list">{['Where context comes from and how knowledge is retrieved', 'Which model receives information and what tools it can use', 'Where decisions happen and what gets remembered', 'What gets evaluated and what happens when something fails'].map((item,index)=><div key={item}><span>0{index+1}</span>{item}</div>)}</div><div className="gx-page-actions"><Button href="/docs/work/architecture" variant="secondary">Explore the Architecture →</Button></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Common integration scenarios" title={<>Integration where architecture meets <em>reality.</em></>} /><div className="gx-offering-grid">{scenarios.map(([title,copy],index)=><article className="gx-offering" key={title}><span>0{index+1}</span><h2 className="gx-display">{title}</h2><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Already have a stack?</div><h2 className="gx-display">Good. We do not need you to start over.</h2><p>Show us what exists, what needs to connect and what is not working. We&apos;ll help determine where intelligence belongs.</p><Button href="/ArchitectureAudit">Talk Through Your Ecosystem →</Button></div></section>
</>; }

const engagementDepths = [
  ['Quick AI Solutions', '$600 – $2,400+', '₹50K – ₹2L+', '3–7 days', 'Focused AI solutions for clearly defined problems where the required system depth is relatively contained.'],
  ['Custom AI Integration / Intelligence Systems', '$2,400 – $7,200+', '₹2L – ₹6L+', '1–2+ weeks', 'For systems requiring deeper integration, knowledge, retrieval, workflows, agents, evaluation or other system-level engineering.'],
  ['Custom Neural R&D / Enterprise', '$7,200 – $24,000+', '₹6L – ₹20L+', 'Custom-scoped', 'For specialized model work, custom neural systems, deeper R&D, enterprise-scale infrastructure or significant investigation and engineering.'],
];
export function PricingExperience() { return <>
  <PageHero kicker="Pricing" title={<>Pricing follows system depth, not a <em>feature checklist.</em></>} copy="A focused AI solution may need a few days of engineering. A persistent intelligence system may require knowledge engineering, memory, evaluation and infrastructure. A research problem may require experimentation before the architecture is even known. We price according to what the problem actually requires."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Start a Conversation →</Button><Button href="/docs/work/architecture" variant="secondary">Explore Architecture</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Problem → Depth → Architecture → Scope → Investment" title={<>Engagement depth, explained <em>clearly.</em></>} copy="USD is the primary reference for international clients; INR is shown as a secondary local equivalent."/><div className="gx-depth-visual"><span>Focused Solution</span><b>↓</b><span>Intelligence System</span><b>↓</b><span>Custom / Enterprise</span><b>↓</b><span>Research & R&amp;D</span></div><div className="gx-pricing-depth-grid">{engagementDepths.map(([title,usd,inr,timing,copy],index)=><article key={title}><span>0{index+1} / ENGAGEMENT DEPTH</span><h2 className="gx-display">{title}</h2><strong>{usd}</strong><small>{inr}</small><em>Typical engagement: {timing}</em><p>{copy}</p><Link href="/ArchitectureAudit">Discuss this engagement →</Link></article>)}</div><p className="gx-currency-note">USD figures are indicative conversions. Final project pricing is quoted in the agreed billing currency.</p></div></section>
  <section className="gx-section gx-audit-pricing"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Architecture Audit</div><h2 className="gx-display">Technical judgment before a <em>bigger commitment.</em></h2></div><div className="gx-copy"><h3>Custom-scoped based on system complexity</h3><p>A high-leverage technical review for systems that need an honest second look. No fixed price is invented; the current audit route and submission flow remain intact.</p><Button href="/ArchitectureAudit">Get Technical Judgment →</Button></div></div></section>
  <section className="gx-section gx-process-band"><div className="gx-container"><SectionHeader kicker="Why pricing varies" title={<>Different systems require different depths of <em>engineering.</em></>} copy="A focused feature may need model integration and application engineering. An intelligence system may need knowledge, retrieval, memory, workflow architecture, evaluation, infrastructure and integrations. A research engagement may need hypothesis development, experimentation, investigation and iteration."/><div className="gx-scope-list">{['Problem complexity', 'Existing system architecture', 'Data availability and quality', 'Model, retrieval and memory requirements', 'Integration, evaluation and infrastructure requirements', 'Security constraints, scale and research uncertainty'].map((item,index)=><div key={item}><span>0{index+1}</span>{item}</div>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="How engagements start" title={<>Make the technical direction <em>clear first.</em></>} /><div className="gx-lifecycle">{[['Understand','Problem, environment, constraints and desired outcome.'],['Determine depth','Focused solution, intelligence system, infrastructure, model work or research.'],['Define scope','Architecture, engineering requirements, risks and deliverables.'],['Quote','Pricing based on actual scope and agreed engagement depth.'],['Build / Research','Work begins once technical direction is clear.']].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div><p className="gx-principle-statement">We don&apos;t price intelligence by the number of features on a page. We price the engineering required to make the system actually work.</p></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Not sure which level your problem requires?</div><h2 className="gx-display">Tell us what you&apos;re trying to build.</h2><p>You do not need to know whether you need an AI solution, intelligence system, custom infrastructure or R&amp;D before talking to us. We&apos;ll help determine the depth required.</p><Button href="/ArchitectureAudit">Start a Conversation →</Button></div></section>
</>; }

export function ResourceLanding({ type }: { type: 'templates' | 'blogs' }) { const isTemplates = type === 'templates'; return <>
  <PageHero kicker={isTemplates ? 'Templates' : 'Blogs'} title={isTemplates ? <>Practical starting points for <em>intelligent systems.</em></> : <>Ideas, research and engineering <em>in progress.</em></>} copy={isTemplates ? 'Reusable knowledge will live here as Genjecx publishes approved system blueprints, workflow patterns and R&D frameworks.' : 'A home for approved Genjecx thinking across systems, engineering, research and company work.'}><div className="gx-page-actions"><Button href="/ArchitectureAudit">Start a conversation</Button><Button href="/docs" variant="secondary">Explore Docs</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container gx-resource-note"><div className="gx-kicker">Growing resource library</div><h2 className="gx-display">{isTemplates ? 'No manufactured marketplace.' : 'No manufactured editorial calendar.'}</h2><p>{isTemplates ? 'There are no verified production templates in the current repository, so this page intentionally provides a focused resource destination rather than inventing downloadable assets.' : 'There are no verified production articles in the current repository, so this page intentionally provides a focused editorial destination rather than inventing authors, dates or claims.'}</p><div><Link href="/docs/research">Research & Development →</Link><Link href="/docs/work">Explore the work →</Link><Link href="/docs/solutions">What Genjecx builds →</Link></div></div></section>
</>; }
