import Link from 'next/link';
import Reviews from './Reviews';
import { Button, SectionHeader } from '@/components/ui/Primitives';

const capabilities = [
  ['01', 'Intelligent Systems', 'Agents, workflows and decision systems built around how your company actually works.'],
  ['02', 'Intelligence Infrastructure', 'The data, knowledge, routing and evaluation layers that make intelligence dependable.'],
  ['03', 'Custom Models', 'Purpose-built models for problems where generic capability is not enough.'],
  ['04', 'Custom Infrastructure', 'Durable technical foundations for systems that need to evolve over time.'],
  ['05', 'AI R&D', 'Research-led experiments for opportunities that do not yet have a standard answer.'],
  ['06', 'Consulting & Advisory', 'Technical judgment before the commitment to build.'],
];
const principles = [['01', 'Own', 'Build intelligence your company can understand, control and grow.'], ['02', 'Evolve', 'Design systems that adapt as your context, data and ambitions change.'], ['03', 'Compound', 'Make each improvement part of the foundation for the next.']];

function Network() { const nodes = [['DATA',100,80],['KNOWLEDGE',290,154],['MODELS',465,72],['AGENTS',590,210],['SYSTEMS',410,305],['FEEDBACK',190,280],['INTELLIGENCE',330,190]] as const; const lines = [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,0],[6,2],[6,4]]; return <svg className="gx-network" viewBox="0 0 680 380" aria-label="An evolving intelligence system"><defs><radialGradient id="gxGlow"><stop stopColor="#ff4fb8" stopOpacity=".65"/><stop offset="1" stopColor="#e91e8c" stopOpacity="0"/></radialGradient></defs>{lines.map(([a,b],i)=><line key={i} x1={nodes[a][1]} y1={nodes[a][2]} x2={nodes[b][1]} y2={nodes[b][2]} className="gx-network-line" style={{animationDelay:`${i*.18}s`}}/>)}{nodes.map(([name,x,y],i)=><g key={name} style={{animation:`gx-network-node 2.8s ease-in-out ${i*.17}s infinite`}}><circle cx={x} cy={y} r={name==='INTELLIGENCE'?48:34} fill="url(#gxGlow)"/><circle cx={x} cy={y} r={name==='INTELLIGENCE'?16:11} className="gx-network-core"/><text x={x} y={y+(name==='INTELLIGENCE'?39:30)} textAnchor="middle">{name}</text></g>)}</svg> }

export default function GenjecxHomepage() { return <>
  <section className="gx-home-hero"><div className="gx-container gx-hero-grid"><div className="gx-reveal"><div className="gx-kicker">Independent AI R&D Studio</div><h1 className="gx-display">Build intelligence<br/>that <em>compounds.</em></h1><p className="gx-copy">Genjecx designs intelligent systems and the infrastructure beneath them—so your company can own, evolve and build on what it learns.</p><div className="gx-hero-actions"><Button href="/ArchitectureAudit">Start a conversation</Button><Button href="/docs" variant="secondary">Explore how we think</Button></div><div className="gx-hero-meta"><span>DATA → SYSTEMS → INTELLIGENCE</span><span>Built for the long run</span></div></div><div className="gx-network-wrap gx-reveal gx-delay-2"><Network /></div></div></section>

  <section className="gx-section gx-differentiator"><div className="gx-container"><SectionHeader kicker="The Genjecx approach" title={<>AI should not be another <span className="gx-gradient-text"><em>layer you rent.</em></span></>} copy="We build systems your company can own, evolve and compound over time." /><div className="gx-principles">{principles.map(([number,title,copy])=><article key={title} className="gx-principle"><span>{number}</span><h3 className="gx-display">{title}.</h3><p>{copy}</p></article>)}</div></div></section>

  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What we build" title={<>From intelligent systems to the <em>infrastructure beneath them.</em></>} copy="We work at the level the problem requires—from clear technical direction to custom systems and deep R&D."/><div className="gx-capabilities">{capabilities.map(([num,title,copy])=><Link href="/docs/solutions" key={title} className="gx-capability"><span>{num}</span><div><h3 className="gx-display">{title}</h3><p>{copy}</p></div><b>→</b></Link>)}</div></div></section>

  <section className="gx-section gx-compounding"><div className="gx-container gx-compound-grid"><div><div className="gx-kicker">Compounding intelligence</div><h2 className="gx-display">Every system should leave you <em>more capable</em> than before.</h2><p className="gx-copy">Knowledge, models, workflows and feedback become a shared intelligence layer—not a collection of disconnected features.</p><Button href="/docs/research" variant="secondary">See the system</Button></div><div className="gx-cycle">{['Data','Knowledge','Models','Agents','Systems','Feedback'].map((item,i)=><div key={item} style={{transform:`rotate(${i*60}deg) translateY(-138px) rotate(${-i*60}deg)`}}><small>{String(i+1).padStart(2,'0')}</small>{item}</div>)}<strong>INTELLIGENCE</strong></div></div></section>

  <section className="gx-section"><div className="gx-container gx-consulting"><div className="gx-consulting-copy"><SectionHeader kicker="Consulting & Advisory" title={<>You do not need to know <em>what to build.</em></>} copy="We turn an ambiguous AI opportunity into a considered system, an architecture and a practical next step."/><Button href="/ArchitectureAudit">Request an architecture audit</Button></div><ol>{[['01','Problem'],['02','Discovery'],['03','Architecture'],['04','Recommendation'],['05','Build']].map(([n,label])=><li key={n}><span>{n}</span>{label}<b>→</b></li>)}</ol></div></section>

  <section className="gx-section gx-research"><div className="gx-container"><SectionHeader kicker="Research & development" title={<>We are building <em>what comes next.</em></>} copy="Research gives the systems we build more depth, more rigor and a longer horizon."/><div className="gx-research-cards">{[['Neural Studio','Experimental intelligence and custom model development.','/docs/research/neural-studio'],['Research & Models','Model philosophy, technical research and applied exploration.','/docs/research/models'],['Architecture','The technical patterns behind durable intelligence systems.','/docs/work/architecture']].map(([title,copy,href],i)=><Link href={href} key={title} className={`gx-research-card card-${i}`}><small>0{i+1} / R&D</small><h3 className="gx-display">{title}</h3><p>{copy}</p><b>Explore →</b></Link>)}</div></div></section>

  <section className="gx-section"><div className="gx-container gx-integrations"><SectionHeader kicker="Ecosystem" title={<>Intelligence does not <em>live alone.</em></>} copy="The right intelligence layer connects with the systems your business already relies on." align="center"/><div className="gx-ecosystem"><span>AI</span><span>Cloud</span><span>Data</span><strong>GEN<span>JECX</span></strong><span>Business</span><span>APIs</span><span>Infrastructure</span></div><div style={{textAlign:'center'}}><Button href="/docs/resources" variant="secondary">Explore the ecosystem</Button></div></div></section>

  <section className="gx-section gx-why"><div className="gx-container"><SectionHeader kicker="Why Genjecx" title={<>For companies that want to build <em>properly.</em></>} /><div className="gx-why-grid">{[['We build, not just integrate.','A solution should fit the real problem, not a vendor’s product category.'],['We think in systems, not features.','The useful question is how intelligence works together over time.'],['We design for ownership.','Your core intelligence should be understandable and extensible.'],['We stay for the long run.','We work with the system as it learns, changes and expands.']].map(([title,copy])=><article key={title}><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>

  <section className="gx-section"><div className="gx-container gx-client-fit"><div><div className="gx-kicker">Who we work with</div><h2 className="gx-display">For ambitious teams<br/>thinking <em>long term.</em></h2></div><div>{['Serious startups','Venture-backed companies','AI-native teams','Companies building complex products'].map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></div></section>

  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Engagements" title={<>The right depth for the <em>right problem.</em></>} copy="We start with the work that will make the greatest long-term difference. Every engagement is shaped around the system, not a generic tier."/><div className="gx-pricing">{[['Advisory','Clarify what should be built.'],['Intelligent Systems','Build AI systems around the business.'],['Intelligence Infrastructure','Build the intelligence foundation.'],['Custom R&D','Build proprietary models and infrastructure.']].map(([title,copy],i)=><article key={title} className={i===2?'featured':''}><small>0{i+1}</small><h3 className="gx-display">{title}</h3><p>{copy}</p><Link href="/ArchitectureAudit">Talk to us →</Link></article>)}</div></div></section>

  <section className="gx-section gx-roadmap"><div className="gx-container"><SectionHeader kicker="Looking forward" title={<>The work is always <em>evolving.</em></>} /><div>{[['NOW','Systems and intelligence foundations'],['NEXT','Research-led capabilities'],['LATER','New infrastructure and tools'],['BEYOND','What is not obvious yet']].map(([time,copy])=><article key={time}><span>{time}</span><p>{copy}</p></article>)}</div></div></section>
  <Reviews />
  <section className="gx-final"><div className="gx-container"><div className="gx-kicker">Build with Genjecx</div><h2 className="gx-display">Build something<br/>worth <em>owning.</em></h2><p>Tell us what you are trying to build. We will help you find the architecture beneath the idea.</p><Button href="/ArchitectureAudit">Start a conversation</Button></div></section>
</>; }
