'use client';

import { useState } from 'react';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { Button, SectionHeader } from '@/components/ui/Primitives';

type Depth = { label: string; title: string; subtitle: string; flow: string[]; fields: string[] };

const depths: Depth[] = [
  { label: '01 / QUICK AI SOLUTIONS', title: 'Quick AI Solutions', subtitle: 'Focused AI Capability', flow: ['Input', 'Context', 'Model', 'Action', 'Evaluation'], fields: ['Project name', 'Problem', 'System type', 'Core architecture', 'Technologies', 'Outcome', 'Diagram'] },
  { label: '02 / CUSTOM AI INTEGRATION', title: 'Custom AI Integration / Intelligence Systems', subtitle: 'Persistent Intelligence', flow: ['Data', 'Knowledge', 'Retrieval', 'Memory', 'Intelligence', 'Evaluation'], fields: ['Problem', 'Intelligence architecture', 'Knowledge layer', 'Memory', 'Agents', 'Evaluation', 'Infrastructure', 'Outcome'] },
  { label: '03 / CUSTOM NEURAL R&D', title: 'Custom Neural R&D / Enterprise', subtitle: 'Research-Driven Intelligence', flow: ['Research', 'Data', 'Neural Architecture', 'Training', 'Inference', 'Evaluation', 'Deployment'], fields: ['Research question', 'Architecture', 'Dataset', 'Training', 'Inference', 'Evaluation', 'Infrastructure', 'Findings'] },
];

export function ResearchStatusStrip() { return <div className="gx-research-status" aria-label="Neural Studio research metadata">{[['Research area', 'Neural Intelligence'], ['Focus', 'Architecture · Training · Inference'], ['Approach', 'Experimental'], ['Output', 'Models · Findings · Systems']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div>; }

export function ResearchDepthSelector() { const [active, setActive] = useState(0); const current = depths[active]; return <section className="gx-section gx-research-depth-selector"><div className="gx-container"><SectionHeader kicker="Research depth" title={<>Architectural depth, not <em>package size.</em></>} copy="Some systems are focused capabilities. Others become persistent intelligence. Some require research-driven engineering."/><div className="gx-research-depth-tabs" role="tablist" aria-label="Research depth">{depths.map((tier,index)=><button key={tier.label} type="button" role="tab" aria-selected={active===index} className={active===index?'active':''} onClick={()=>setActive(index)}><span>{tier.label}</span><strong className="gx-display">{tier.title}</strong><small>{tier.subtitle}</small><i>{tier.flow.slice(0,4).join(' → ')}</i></button>)}</div><section className="gx-research-depth-panel" role="tabpanel" aria-live="polite"><span>{current.label}</span><h3 className="gx-display">{current.title}</h3><p>{current.subtitle}</p><FlowDiagram label={`${current.title} architecture`} steps={current.flow}/><div className="gx-project-rows"><b>PROJECTS / ACTIVE TIER</b>{current.fields.map((field,index)=><div key={field}><span>0{index+1}</span><strong>{field}</strong><small>Documented where approved project material is available.</small></div>)}</div></section></div></section>; }

export function ResearchComparisonMatrix() { const rows = [['Primary goal','Solve a bounded problem','Build an intelligence system','Solve a technically difficult problem'],['Agents','✓','✓','✓'],['RAG','✓','✓','✓'],['Integrations','✓','✓','✓'],['Custom data engineering','—','✓','✓'],['Persistent memory','—','✓','✓'],['Knowledge graphs','—','✓','✓'],['Evaluation pipelines','—','✓','✓'],['Custom neural networks','—','—','✓'],['Custom training','—','—','✓'],['Deterministic inference','—','—','✓'],['Neuro-symbolic systems','—','—','✓']]; return <section className="gx-section gx-research-comparison"><div className="gx-container"><FlowDiagram label="Architectural depth" steps={['Tier 01 / Focused capability','Tier 02 / Persistent intelligence','Tier 03 / Research-driven intelligence']} /><SectionHeader kicker="What changes between tiers?" title={<>A technical comparison, not a <em>pricing table.</em></>} /><div className="gx-research-matrix" role="table" aria-label="Research depth comparison"><div role="row" className="head"><b>Capability</b><b>Tier 1</b><b>Tier 2</b><b>Tier 3</b></div>{rows.map(([label,a,b,c])=><div role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{a}</span><span role="cell">{b}</span><span role="cell">{c}</span></div>)}</div><p className="gx-principle-statement">The tiers are not arbitrary packages. They represent increasing architectural depth.</p></div></section>; }

export function ResearchKnowledge() { return <section className="gx-section gx-research-knowledge"><div className="gx-container"><SectionHeader kicker="What becomes knowledge" title={<>Research → Experiment → Validate → <em>Generalize.</em></>} /><div>{[['Products','Some research becomes something people use.'],['Architectures','Some research becomes reusable system patterns.'],['Findings','Some research simply answers a question.']].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div><p className="gx-principle-statement">Not every question needs a product. Some need an experiment. Some need a system. Some need research.</p><div className="gx-page-actions"><Button href="/docs/research/neural-studio" variant="secondary">Explore Neural Studio →</Button><Button href="/ArchitectureAudit" variant="secondary">Talk to GenJecX →</Button></div></div></section>; }
