import Link from 'next/link';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { Button, PageHero, SectionHeader } from '@/components/ui/Primitives';
import AuditCTA from './AuditCTA';

const auditAreas = [
  ['System Architecture', 'How the pieces fit together', 'Component boundaries · Service architecture · Data flow · Model placement · Agent orchestration · Dependencies · Scalability · Failure boundaries', 'Is the architecture solving the problem—or just connecting components together?'],
  ['Model Strategy', 'Why these models?', 'Model selection · Model routing · Prompt architecture · Context windows · Fine-tuning · Training strategy · Model redundancy · Latency · Cost · Performance', 'Is the model actually the right layer to solve this problem?'],
  ['Data & Knowledge', 'What does the system know, and how does it access it?', 'Data sources · Data quality · Transformation · Chunking · Embeddings · Retrieval · Knowledge structures · Freshness · Metadata · Memory', 'Does the system have access to the right information at the right time?'],
  ['Infrastructure', 'What does it actually cost to run?', 'Compute · Storage · Databases · Model hosting · APIs · Networking · Scaling · Deployment · Observability', 'Can this architecture operate reliably at the expected scale and cost?'],
  ['Evaluation', 'How do you know it works?', 'Evaluation datasets · Metrics · Retrieval evaluation · Model evaluation · Agent evaluation · Regression testing · Human evaluation · Production feedback', 'What evidence supports the claim that the system works?'],
  ['Failure Modes', "What happens when it doesn't?", 'Hallucination · Retrieval failure · Model failure · Tool failure · Agent loops · Data failure · API failure · Timeout behavior · Recovery · Fallbacks', 'What happens when the system is wrong?'],
  ['Cost, Risk & Efficiency', 'Where is the system leaking value?', 'Token usage · Model spend · Infrastructure cost · Latency · Redundant processing · Unnecessary model calls · Scaling assumptions · Vendor dependencies · Security concerns · Operational risk', 'What will become expensive, fragile, or risky as the system grows?'],
];
const inspection = [['Data Flow','Where does information enter? How is it transformed, stored and assembled into model context? Where can information be lost?'],['Models','Why this model for this problem? Is routing appropriate, fine-tuning justified and the context strategy sound?'],['Retrieval','What gets retrieved, why, how is relevance measured and what happens when retrieval fails?'],['Agents','What decisions are autonomous, what requires deterministic control and what happens when an agent is wrong?'],['Infrastructure','What happens under load, where are the bottlenecks and what infrastructure is unnecessary?'],['Evaluation','What does good mean? Is there a test set, failure tracking, regression detection and human judgment where needed?']];
const deliverables = [['Audit Report','A structured technical assessment of the system.'],['Architecture Map','A visual representation of how the system currently works.'],['Risk Cards','Prioritized technical risks with severity and impact.'],['Model Assessment',"What is working, what isn't, and what should change."],['Data Strategy Assessment','Evaluation of data quality, structure, retrieval and knowledge architecture.'],['Infrastructure Assessment','Cost, scaling, deployment and operational concerns.'],['Cost Analysis','Where compute and model costs originate and where optimization may exist.'],['Prioritized Roadmap','Fix now · Fix next · Monitor · Don’t touch.']];

export function AuditExperience() { return <>
  <PageHero kicker="AI Architecture Audit" title={<>Find what&apos;s actually broken before you <em>build more.</em></>} copy="You have an AI system. Or you’re about to build one. Something isn’t working—or you’re not confident the architecture you’re about to commit to is right. We examine the system, identify technical risks and bottlenecks, and give you a concrete path forward. No pitch deck. No forced rebuild. Just technical judgment." />
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Why an audit?" title={<>The visible failure isn&apos;t always the <em>actual failure.</em></>} copy="AI systems can fail at layers that aren’t obvious from the interface. We look underneath it."/><div className="gx-audit-failure-map">{['A good model but poor retrieval.','Good retrieval but bad context construction.','Good prompts but weak evaluation.','Good models but excessive infrastructure cost.','Good components but poor orchestration.','A working prototype but an architecture that won’t survive production.'].map((item,i)=><article key={item}><span>0{i+1}</span><p>{item}</p></article>)}</div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="What we audit" title={<>Seven layers of <em>technical inspection.</em></>} /><div className="gx-audit-area-grid">{auditAreas.map(([title,subtitle,items,question],i)=><article key={title}><span>0{i+1}</span><h3 className="gx-display">{title}</h3><b>{subtitle}</b><p>{items}</p><small>{question}</small></article>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Audit framework" title={<>The system before the <em>recommendation.</em></>} /><div className="gx-audit-framework" aria-label="AI architecture audit framework"><b>AI SYSTEM</b><div><span>DATA</span><span>MODEL</span><span>ARCHITECTURE</span></div><b>INTELLIGENCE</b><div><span>EVALUATION</span><span>INFRASTRUCTURE</span><span>FAILURE MODES</span></div><b>COST + RISK</b><strong>RECOMMENDATIONS</strong></div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="What we actually look for" title={<>Inspection at the layer where it <em>matters.</em></>} /><div className="gx-research-area-grid">{inspection.map(([title,copy],i)=><article className="gx-research-area" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What you receive" title={<>Evidence, maps and a <em>path forward.</em></>} /><div className="gx-audit-deliverables">{deliverables.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p>{title==='Risk Cards'&&<aside><b>HIGH</b><strong>Retrieval Context Loss</strong><p>Relevant information is available in the knowledge base but is not consistently reaching the model.</p><small>Recommendation: Rework retrieval + context assembly.</small></aside>}</article>)}</div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="Five questions" title={<>From inspection to the <em>next decision.</em></>} /><FlowDiagram label="Audit decision path" steps={['What is working?','What is broken?','Why is it broken?','What should change?','What should happen next?']} /></div></section>
  <section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">What this is not</div><h2 className="gx-display">A sales demo with a <em>diagnostic label.</em></h2></div><div className="gx-copy gx-audit-not-list">{[['Not a Sales Demo','You aren’t paying for a product pitch.'],['Not a Generic AI Consultation','The assessment is based on your actual system.'],['Not a Guaranteed Rebuild','An audit may conclude that your existing architecture is sufficient.'],['Not a Benchmark Report','We assess the system as a whole—not just model scores.'],['Not a Promise to Fix Everything','The purpose is to establish what actually needs fixing.']].map(([title,copy])=><p key={title}><b>{title}</b><br/>{copy}</p>)}</div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="Who it&apos;s for" title={<>Technical confidence before the <em>next commitment.</em></>} /><div className="gx-audit-failure-map">{[['Founders','You’ve built an AI product and need technical confidence before scaling.'],['CTOs / Engineering Leads','You want an independent assessment of architectural decisions.'],['Product Teams','You’re unsure whether the next investment should be another feature or an architectural change.'],['Teams with a Stalled AI Initiative','You’ve tried several approaches and still don’t have a reliable system.'],['Teams Before a Major Build','You want technical judgment before committing significant engineering resources.']].map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="gx-audit-do-dont"><div><b>YOU PROBABLY DON&apos;T NEED ONE IF</b><p>You have a tiny prototype, a well-understood problem, a simple API integration, or no meaningful architectural decisions yet.</p></div><div><b>YOU PROBABLY SHOULD CONSIDER ONE IF</b><p>Costs are growing unexpectedly, performance is inconsistent, components are difficult to manage, retrieval is unreliable, agents are unpredictable, or a major architecture investment is next.</p></div></div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="How the audit works" title={<>An inspection, then a <em>decision.</em></>} /><FlowDiagram label="Architecture audit engagement flow" steps={['Submit','Scope','Inspect','Report','Review','Decide']} /><p className="gx-principle-statement">The next step may be with us—or without us.</p></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Architecture audit</div><h2 className="gx-display">Know something is wrong, but not <em>where?</em></h2><p>Don&apos;t spend another month changing models, rewriting prompts or adding infrastructure without knowing the actual bottleneck.</p><Button href="#audit-request">Request an Architecture Audit →</Button><Link className="gx-button secondary" href="/ArchitectureAudit">Talk Through Your System →</Link></div></section><div id="audit-request"><AuditCTA/></div>
</>; }
