import Link from 'next/link';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { Button, SectionHeader } from '@/components/ui/Primitives';

export function TemplateFramework() { const fields = ['Problem', 'When to use it', 'Architecture', 'Inputs', 'Process', 'Evaluation', 'Failure modes', 'Adaptation notes', 'When not to use it']; return <section className="gx-section gx-template-framework"><div className="gx-container"><SectionHeader kicker="Reusable technical patterns" title={<>Templates should explain a <em>system</em>, not imitate best practice.</>} copy="A lightweight framework for reusable system blueprints, workflow patterns, architecture patterns, evaluation and research frameworks. No template inventory is claimed until verified material exists."/><div className="gx-template-card"><span>TEMPLATE / STRUCTURE</span><FlowDiagram label="Miniature system map" steps={['Problem', 'Architecture', 'Process', 'Evaluation']} /><dl>{fields.map((field,index)=><div key={field}><dt>0{index+1} / {field}</dt><dd>{field === 'When not to use it' ? 'State the constraint, risk or mismatch before adapting this pattern.' : 'Documented when an approved pattern is available.'}</dd></div>)}</dl></div></div></section>; }

export function EditorialFramework() { return <section className="gx-section gx-editorial-framework"><div className="gx-container"><SectionHeader kicker="Editorial principle" title={<>Ideas, research &amp; engineering <em>in progress.</em></>} copy="Posts should be things GenJecX actually believes, tested, built, learned or researched—not a generic SEO calendar."/><div className="gx-editorial-grid">{[['System Engineering','Architecture, agents, retrieval, infrastructure and evaluation.'],['Research','Experiments, models, exploration, failures and discoveries.'],['Applied AI','What happens when intelligence meets real operating problems.'],['Build Notes','Technical decisions behind systems we build.'],['Founder Notes','How we think about building an R&D studio.']].map(([title,copy],index)=><article key={title}><span>0{index+1} / QUESTION → INVESTIGATION → FINDING</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>; }

export function DocsKnowledgeGraph() { return <section className="gx-section gx-docs-graph"><div className="gx-container"><SectionHeader kicker="Genjecx knowledge graph" title={<>The technical knowledge layer of the <em>website.</em></>} copy="Build, research, architecture, patterns and resources are connected views of the same system."/><FlowDiagram label="Knowledge system" steps={['Build', 'Research', 'Architecture', 'Patterns', 'Resources']} /></div></section>; }

export function ConversationPaths() { return <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Talk to GenJecX" title={<>Have a system in mind? Have a system that&apos;s broken? <em>Start there.</em></>} copy="You don’t need a perfect brief. Give us the actual situation: a product idea, architecture, technical problem, research question or existing system."/><div className="gx-conversation-paths">{[['Build Something','You know what you want to create.'],['Fix Something','You already have a system and something is not working.'],['Figure Something Out','You have the problem but not the technical answer yet.']].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div><FlowDiagram label="Conversation path" steps={['Technical judgment', 'System']} /><Button href="/ArchitectureAudit">Discuss the system</Button></div></section>; }

export function ResourcesContext() { return <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Resources & ecosystem" title={<>Context, not empty <em>promises.</em></>} copy="The technology, reusable patterns, research and ecosystem context around GenJecX systems—only where it helps explain how a system could actually work."/><div className="gx-resource-context-grid">{[['Integration','Fit the system to the real environment.','/integrations','Explore Integration'],['Templates','Reusable architectures and system patterns with a clear reason to exist.','/templates','Explore Templates'],['Roadmap','Direction, not theatre.','/roadmap','See the Roadmap'],['FAQ','Clear answers before the next decision.','/faq','Read the FAQ']].map(([title,copy,href,cta],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p><Link href={href}>{cta} →</Link></article>)}</div></div></section>; }

export function DecisionGuides() { const guides = ['Build vs Integrate', 'Agent vs Workflow', 'RAG vs Fine-Tuning', 'Custom Model vs Existing Model', 'Local vs Hosted Models', 'Vector Database vs Knowledge Graph', 'Prototype vs Production', 'Automation vs Intelligence']; return <section className="gx-section gx-decision-guides"><div className="gx-container"><SectionHeader kicker="Decision guides" title={<>Better context. Better <em>decisions.</em></>} copy="Technical resources for understanding AI systems before committing engineering time or money. These are decision frameworks, not generic SEO posts or claims about measured results."/><div className="gx-decision-guide-grid">{guides.map((title,index)=><article key={title}><span>GUIDE / 0{index+1}</span><h3 className="gx-display">{title}</h3><FlowDiagram label="Decision framework" steps={['Question', 'Context', 'Criteria', 'Trade-offs', 'Next decision']} /><p><b>When not to use:</b> when the underlying problem, data, constraints or expected outcome have not been understood.</p><Link href="/ArchitectureAudit">Discuss the decision →</Link></article>)}</div></div></section>; }
