import Link from 'next/link';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { Button, SectionHeader } from '@/components/ui/Primitives';

const build = [['Intelligent Systems','/docs/solutions'],['Intelligent Infrastructure','/docs/work/architecture'],['Custom Models','/docs/research/models'],['Custom Infrastructure','/docs/work/architecture'],['AI R&D','/docs/research'],['Consulting & Advisory','/docs/work/architecture-audits']];
const explore = ['Intelligence architectures','Neural systems','Knowledge & memory','Agent systems','Evaluation','Model efficiency','Applied intelligence'];

const stackLayers = [
  ['Application', 'Products • Workflows • Interfaces'],
  ['Intelligence', 'Agents • Reasoning • Decisions • Actions'],
  ['Knowledge & Memory', 'Retrieval • Graphs • Context • Memory'],
  ['Models', 'Hosted • Local • Custom • Hybrid'],
  ['Evaluation', 'Reliability • Cost • Quality • Feedback'],
  ['Infrastructure', 'Data • Compute • APIs • Observability'],
];

export function IntelligenceStack({ focus }: { focus?: 'models' | 'infrastructure' | 'research' } = {}) {
  return <section className="gx-intelligence-stack" aria-label="GenJecX Intelligence Stack. Research and development informs application, intelligence, knowledge and memory, models, evaluation and infrastructure.">
    <div className="gx-stack-rd"><span>R&amp;D</span><small>Research informs every layer</small></div>
    <div className="gx-stack-layers">{stackLayers.map(([name, details], index) => <article key={name} className={focus === 'models' && name === 'Models' || focus === 'infrastructure' && ['Knowledge & Memory', 'Evaluation', 'Infrastructure'].includes(name) ? 'highlight' : ''}><span>0{index + 1}</span><strong>{name}</strong><small>{details}</small></article>)}</div>
  </section>;
}

export function EverythingAtAGlance() { return <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Everything at a glance" title={<>The shortest path to understanding what GenJecX <em>builds, explores and believes.</em></>} /><FlowDiagram label="The Genjecx system map" steps={['Problem','Intelligence','Knowledge','Architecture','Evaluation','Infrastructure','Iteration']} /><div className="gx-glance-grid"><article><span>WHAT WE BUILD</span>{build.map(([name,href])=><Link key={name} href={href}>{name}<b>→</b></Link>)}</article><article><span>WHAT WE&apos;RE EXPLORING</span>{explore.map((name,index)=><p key={name}><b>0{index + 1}</b>{name}</p>)}</article><article><span>USEFUL CONTEXT</span>{[['Architecture','/docs/work/architecture'],['Case Studies','/docs/work/case-studies'],['Templates','/templates'],['Research','/docs/research'],['Integrations','/integrations'],['FAQ','/faq'],['Roadmap','/roadmap']].map(([name,href])=><Link key={name} href={href}>{name}<b>→</b></Link>)}</article></div></div></section>; }

export function HowWeWork() { const stages = [['Understand','Problem, users, systems, data, constraints and outcome.'],['Decompose','Product, data, model, system and infrastructure questions.'],['Decide','Integrate, build, customize or research.'],['Architect','Data flow, intelligence, model strategy, retrieval, memory and evaluation.'],['Prototype','The highest-risk assumptions first.'],['Evaluate','Whether the system actually works.'],['Build','Production only after the architecture survives the important questions.'],['Improve','Feedback, evaluation, new knowledge and iteration.']]; return <section className="gx-section gx-how-work"><div className="gx-container"><SectionHeader kicker="How we work" title={<>We don&apos;t start by deciding what to build. We start by understanding what needs to be <em>true.</em></>} /><div className="gx-lifecycle">{stages.map(([title,copy],index)=><article key={title}><span>0{index + 1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div><p className="gx-principle-statement">We build the brain before polishing the face.</p></div></section>; }

export function ArchitecturePatterns() { const patterns: Array<[string, string[]]> = [['Retrieval',['Documents','Embeddings','Retrieval','Context','Reasoning']],['Memory',['Interaction','Extraction','Storage','Retrieval','Future context']],['Agent Orchestration',['Goal','Planner','Specialist agents','Tools','Validation','Result']],['Evaluation',['Input','Output','Evaluator','Score','Feedback']],['Knowledge Engineering',['Raw information','Entities','Relationships','Knowledge graph','Retrieval']],['Model Routing',['Problem','Classifier','Model selection','Inference','Evaluation']]]; return <section className="gx-section gx-patterns"><div className="gx-container"><SectionHeader kicker="The patterns underneath" title={<>Projects may look different. The underlying architecture often <em>isn&apos;t.</em></>} copy="These are conceptual patterns, not claims about a specific client implementation."/><div className="gx-pattern-grid">{patterns.map(([title,steps],index)=><article key={title}><span>PATTERN / 0{index + 1}</span><h3 className="gx-display">{title}</h3><FlowDiagram label={title} steps={steps} /></article>)}</div></div></section>; }

export function ArchitectureLayers() { const layers = [['Data','What information enters the system?'],['Knowledge','How is information structured and understood?'],['Retrieval','How does the system find the right context?'],['Intelligence','What reasons, predicts, generates or decides?'],['Memory','What does the system remember?'],['Tools','What can it actually do?'],['Evaluation','How do we know it is working?'],['Infrastructure','Can it operate reliably at scale?']]; return <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Architecture" title={<>Architecture is where AI becomes a <em>system.</em></>} copy="A model can generate an answer. An architecture determines whether that answer is useful."/><FlowDiagram label="Core architecture layers" steps={layers.map(([title])=>title)} /><div className="gx-layer-grid">{layers.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div><p className="gx-principle-statement">The feature is the visible part. The architecture is what makes it durable.</p></div></section>; }

export function AuditSample() { const areas = ['System Architecture','Model Strategy','Data & Knowledge','Infrastructure','Evaluation','Cost & Efficiency','Risk']; return <section className="gx-section gx-audit-sample"><div className="gx-container"><SectionHeader kicker="Sample / example artifact" title={<>An honest second look at the <em>system.</em></>} copy="This sample demonstrates the structure of an AI Architecture Audit. It is not a client audit and contains no client data or findings."/><div className="gx-sample-report"><header><span>SAMPLE AI ARCHITECTURE AUDIT REPORT</span><b>EXAMPLE ONLY</b></header><div>{areas.map((area,index)=><article key={area}><span>0{index+1}</span><h3>{area}</h3><p>Assessment area, risks, evidence and prioritized recommendations.</p></article>)}</div><footer>System assessment → architecture maps → risk cards → cost analysis → recommendations → next-step architecture</footer></div></div></section>; }

export function EcosystemConversation() { return <section className="gx-section gx-ecosystem-talk"><div className="gx-container"><SectionHeader kicker="Talk through your ecosystem" title={<>Your stack doesn&apos;t need to be clean. It needs to be <em>understood.</em></>} copy="Tell us what already exists: systems, data, models, bottlenecks and the connections that are missing."/><FlowDiagram label="Ecosystem map" steps={['Data','Applications','APIs','Models','Infrastructure','Users']} /><div className="gx-question-grid">{['What systems do you already use?','Where does your data live?','Which AI models are currently in production?','What systems need to communicate?','What currently feels disconnected?','Where are the bottlenecks?','What are you trying to add?'].map((question,index)=><article key={question}><span>0{index+1}</span><p>{question}</p></article>)}</div><div className="gx-page-actions"><Button href="/ArchitectureAudit">Map the ecosystem</Button><Button href="/docs/work/architecture" variant="secondary">Read about architecture</Button></div></div></section>; }
