import Link from 'next/link';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { SectionHeader } from '@/components/ui/Primitives';

const questions = [['What needs to be learned?', 'What information or behavior does the system actually need to acquire?'], ['What needs to be represented?', 'Can the problem be represented effectively using existing model structures?'], ['What needs to be deterministic?', 'Where should the system behave predictably rather than probabilistically?'], ['What needs to generalize?', 'Does the system need to work beyond its training examples?'], ['What needs to be optimized?', 'Accuracy? Latency? Memory? Compute? Cost? Reliability?'], ["What isn't working with existing approaches?", 'This determines whether research is justified at all.']];
const directions = [['Neural Architectures', 'Purpose-built architectures for problems where generic architectures may not provide the required behavior.', 'RNN-based systems · CNN-based systems · Hybrid architectures · Specialized representation layers · Architecture modifications · Task-specific networks'], ['Training Systems', 'We investigate how models learn, not simply how to call them.', 'Dataset construction · Training objectives · Loss functions · Optimization · Data preprocessing · Training stability · Generalization · Transfer learning · Fine-tuning strategies'], ['Inference', "A model isn't finished when training ends.", 'Inference latency · Determinism · Memory requirements · Quantization · Model optimization · Local inference · Compute requirements · Production behavior'], ['Hybrid Intelligence', "Some problems shouldn't be solved entirely by neural networks.", 'Neural Models + Rules + Retrieval + Structured Knowledge + Deterministic Logic']];
const currentDirections = [['Specialized Neural Architectures', 'Exploring architectures designed around the structure of specific problems.'], ['Efficient Intelligence', 'Reducing compute, latency, and infrastructure requirements.'], ['Controlled Inference', 'Investigating systems where predictable behavior matters.'], ['Hybrid Intelligence', 'Combining neural learning with structured reasoning.'], ['Persistent Intelligence', 'Exploring how systems can maintain useful context and knowledge over time.'], ['Evaluation', 'Building better ways to measure intelligence beyond benchmark scores.']];
const artifact = [['Research Question', 'What were we trying to find out?'], ['Baseline', 'What existing approach were we comparing against?'], ['Architecture', 'What did we build?'], ['Experiment', 'What changed?'], ['Evaluation', 'How did we measure it?'], ['Result', 'What happened?'], ['Decision', 'What did the result tell us?']];

export function NeuralStudioPhase21() { return <>
  <section className="gx-section gx-neural-intro"><div className="gx-container"><SectionHeader kicker="What Neural Studio is" title={<>The research end of <em>GenJecX.</em></>} copy="Neural Studio is where we experiment with custom neural architectures, specialized models, training strategies, representation learning, inference systems, model optimization, hybrid architectures, deterministic components, neuro-symbolic approaches and domain-specific intelligence."/><p className="gx-principle-statement">Some experiments become production systems. Some become reusable architectures. Some simply tell us what doesn’t work. All three are valuable.</p></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="The question comes first" title={<>We don&apos;t start by choosing a <em>model.</em></>} copy="We start with the technical question."/><div className="gx-question-grid gx-neural-question-grid">{questions.map(([title, copy], i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Neural Studio loop" title={<>Research that reaches a <em>decision.</em></>} /><FlowDiagram label="Neural Studio research loop" steps={['Question','Hypothesis','Architecture','Experiment','Evaluation','Decision','Question']} /><div className="gx-editorial-rows gx-neural-loop-notes">{[['Question','Define the technical problem.'],['Hypothesis','Form a testable assumption about what might work.'],['Architecture','Design the smallest system capable of testing that assumption.'],['Experiment','Train, run, compare, and observe.'],['Evaluation','Measure against a meaningful baseline.'],['Decision','Continue, modify, generalize, or stop.']].map(([title,copy],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="What we explore" title={<>Research around the system, not just the <em>model.</em></>} /><div className="gx-neural-exploration-grid">{directions.map(([title,copy,items],i)=><article key={title}><span>0{i+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p><small>{items}</small></article>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="Research artifacts" title={<>A research notebook, not a <em>service card.</em></>} /><div className="gx-artifact-notebook">{artifact.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="gx-example-research"><span>EXAMPLE RESEARCH CARD</span><h3 className="gx-display">Generic Intelligence Model</h3><p>Tier 3 — Neural R&amp;D</p><p>A research project exploring a purpose-built neural architecture for general-purpose intelligence behavior rather than relying exclusively on a conventional API-driven LLM stack.</p><div>{['Architecture','Training','Inference','Evaluation','Findings'].map(item=><button type="button" key={item}>{item} →</button>)}</div></div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="Current research directions" title={<>The questions that remain <em>open.</em></>} /><div className="gx-research-area-grid">{currentDirections.map(([title,copy],i)=><article className="gx-research-area" key={title}><span>R{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="What makes an experiment worth running?" title={<>Research is not a badge. It&apos;s a <em>tool.</em></>} /><div className="gx-criteria-list">{['Existing models perform poorly on the target problem.','The problem has unusual constraints.','Generic models are unnecessarily expensive.','Latency or compute requirements matter.','Deterministic behavior is important.','The domain requires specialized representations.','Existing approaches leave a meaningful technical gap.','The potential value justifies experimentation.'].map((item,i)=><span key={item}>0{i+1} — {item}</span>)}</div><p className="gx-principle-statement">If an existing model solves the problem well, we use it. If it doesn&apos;t, we investigate why.</p></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="Neural Studio → Production" title={<>Research should eventually become <em>useful.</em></>} /><FlowDiagram label="Research to production" steps={['Experiment','Validated Architecture','Prototype','Production System','Reusable Pattern']} /><p className="gx-principle-statement">Not every experiment makes the journey. That&apos;s intentional.</p></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">R&amp;D problem</div><h2 className="gx-display">Have a problem that existing AI can&apos;t solve <em>well?</em></h2><p>Bring us the constraint. We&apos;ll determine whether it needs better integration, better architecture, or actual research.</p><Link className="gx-button gx-button-primary" href="/ArchitectureAudit">Discuss an R&amp;D Problem →</Link></div></section>
</>; }
