'use client';

import { useState } from 'react';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { Button, PageHero, SectionHeader } from '@/components/ui/Primitives';

const capabilityNames = ['Intelligent Systems', 'Intelligent Infrastructure', 'Custom Models', 'Custom Infrastructure', 'AI R&D', 'Consulting & Advisory'];
const faq = [
  ['What is GenJecX?', 'GenJecX is an AI R&D studio building intelligent systems, infrastructure, custom models and research-led AI solutions.'],
  ['Are you an AI consultancy?', 'Not primarily. Technical advisory is available when judgment is needed, but the core work is building and researching systems.'],
  ['Do you only work with startups?', 'No. We work with startups, product companies, technology teams, founders and organizations facing technically meaningful AI problems.'],
  ['Do you build AI agents?', 'Yes, when agents are actually appropriate to the problem.'],
  ['Do you build custom models?', 'Yes — but only when existing models cannot reasonably satisfy the requirement.'],
  ['Can you work with an existing AI product?', 'Yes. Existing systems can be audited, rearchitected, improved or extended.'],
  ['Can you work with our existing infrastructure?', 'Yes. Integration is designed around the environment already in place.'],
  ['Do you replace existing systems?', 'Not automatically. The goal is to improve the system, not replace technology simply because we did not build it.'],
  ['Do you work with confidential data?', 'Projects can be structured around appropriate security, access, deployment and data-handling requirements.'],
  ['How do projects start?', 'Usually with a conversation or technical assessment. Explaining the problem is enough to begin.'],
  ['How long does a project take?', 'It depends on depth. Focused AI solutions can be relatively short engagements; custom intelligence systems and R&D require more involved engineering.'],
  ['How do you decide what to build?', 'By evaluating the problem, data, model requirements, system architecture, constraints and expected outcome.'],
  ['Do you provide ongoing support?', 'Depending on the system, this can include maintenance, evaluation, optimization, infrastructure support and continued R&D.'],
];

export function AboutExperience() {
  return <><PageHero kicker="About GenJecX" title={<>An AI R&amp;D studio for systems that <em>keep becoming more useful.</em></>} copy="GenJecX works with companies that need more than a surface-level AI feature. We build intelligent systems, infrastructure, custom models and research-led technology around problems where generic capability isn’t enough."><div className="gx-page-actions"><Button href="/products">What we build</Button><Button href="/ArchitectureAudit" variant="secondary">Talk to GenJecX</Button></div></PageHero><section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Why GenJecX exists</div><h2 className="gx-display">Reliable intelligence is not becoming <em>proportionally easier.</em></h2></div><div className="gx-copy"><p>AI is becoming easier to access. The difficult questions are what the system should know, remember and decide; what should remain deterministic; how behavior should be evaluated; and how the system should evolve.</p><p>That is where we work.</p></div></div></section><section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="What we believe" title={<>The model is only <em>one layer.</em></>} /><div className="gx-about-principles">{['AI is a system, not a feature.', 'The model is only one layer.', 'Research belongs close to engineering.', 'Evaluation is part of intelligence.', 'Architecture determines durability.', 'The right answer is not always more AI.'].map((title,index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>Designed around the problem, its operating environment and the system’s ability to improve over time.</p></article>)}</div></div></section><section className="gx-section"><div className="gx-container"><SectionHeader kicker="What we build" title={<>We build the system, not just the <em>feature.</em></>} /><div className="gx-about-principles">{capabilityNames.map((title,index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>One capability within a connected intelligence system.</p></article>)}</div><FlowDiagram label="GenJecX philosophy" steps={['Research', 'Architecture', 'Engineering', 'Evaluation', 'Intelligence']} /></div></section><section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="Founder-led" title={<>Built with curiosity. Run with <em>rigor.</em></>} copy="Garima Kalra — Founder, GenJecX. Founder-led R&D studio focused on turning ambiguous AI problems into working technical systems."/><p className="gx-principle-statement">Research when the answer isn’t obvious. Evaluate instead of assuming. Design for iteration. Care about what happens after the demo.</p></div></section></>;
}

const careerValues = [['Curiosity','Understand why something works, not just make it work once.'],['Ownership','Move an ambiguous problem toward a real answer.'],['High Standards','Care about architecture, reliability, clarity and details.'],['Research Mindset','Test assumptions and change your mind when evidence says so.'],['System Thinking','Understand that the model is only one layer of the system.'],['Long-Term Default','Build things that can survive their first successful demo.'],['Generous With Rigor','Challenge ideas without making the room worse for everyone.']];
export function CareersExperience() {
  const roles = ['AI Engineer', 'Full-Stack AI Engineer', 'Backend / Systems Engineer', 'ML Engineer', 'Research Engineer', 'ML Researcher', 'AI Research Intern', 'AI Engineering Intern', 'Software Engineering Intern', 'Research Intern'];
  return <><PageHero kicker="Careers" title={<>Build the systems that <em>matter next.</em></>} copy="We’re interested in people who are curious about intelligence, rigorous about systems and willing to think beyond the next short-term milestone."><div className="gx-page-actions"><Button href="mailto:genjecx@gmail.com">Introduce yourself</Button><Button href="/about" variant="secondary">About GenJecX</Button></div></PageHero><section className="gx-section"><div className="gx-container"><SectionHeader kicker="Who belongs here?" title={<>Curious, systems-minded and <em>research-oriented.</em></>} /><div className="gx-careers-values">{careerValues.map(([title,copy])=><article key={title}><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="gx-section gx-soft-band"><div className="gx-container"><div className="gx-two-column"><div><div className="gx-kicker">What working here looks like</div><h2 className="gx-display">The work changes. The <em>standard doesn’t.</em></h2></div><div className="gx-copy"><p>One day could involve building an agent, debugging retrieval, designing an evaluation pipeline, researching a model, reviewing architecture, writing infrastructure, testing a hypothesis or deciding not to build something.</p></div></div><div className="gx-theme-row">{roles.map((role,index)=><span key={role}><b>0{index+1}</b>{role}</span>)}</div><p className="gx-principle-statement">We don’t hire people to fill a checklist. We hire people who can think, build, learn and take ownership of difficult problems.</p></div></section></>;
}

const roadmap = [['Stronger Intelligent Systems','Agents, multi-agent systems, decision systems, memory, context and workflow intelligence.'],['Deeper Intelligence Infrastructure','Knowledge engineering, retrieval, knowledge graphs, evaluation, model routing and observability.'],['Custom Intelligence','Specialized models, custom architectures, deterministic inference and hybrid systems.'],['Neural R&D','Neural architectures, training systems, inference, model optimization and neuro-symbolic approaches.'],['Applied Research','Specialized intelligence across healthcare, fitness, enterprise, personal intelligence and research—without unsupported outcomes.'],['Reusable Intelligence','Architecture patterns, templates, evaluation frameworks, research frameworks and system blueprints.']];
export function RoadmapExperience() { return <><PageHero kicker="Roadmap" title={<>A direction of <em>travel.</em></>} copy="Not a list of empty promises. GenJecX&apos;s roadmap is organized around stronger systems, deeper research and more durable intelligence infrastructure."/><section className="gx-section"><div className="gx-container"><FlowDiagram label="Direction map" steps={['Now', 'Explore', 'Validate', 'Build', 'Generalize']} /><div className="gx-roadmap-full">{roadmap.map(([stage,copy],index)=><article key={stage}><span>0{index+1}</span><h2 className="gx-display">{stage}</h2><p>{copy}</p></article>)}</div><p className="gx-principle-statement">We don&apos;t publish dates simply to make the roadmap look busy. We publish direction when there is something meaningful behind it.</p></div></section></>; }

export function FAQExperience() { const [open,setOpen] = useState<number | null>(0); return <><PageHero kicker="FAQ" title={<>Clear answers before the <em>next decision.</em></>} copy="A practical introduction to how GenJecX thinks about intelligent systems, architecture and long-term technical work."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Discuss your system</Button><Button href="/docs" variant="secondary">Explore Docs</Button></div></PageHero><section className="gx-section"><div className="gx-container gx-faq-wrap">{faq.map(([question,answer],index)=><div className="gx-faq-item" key={question}><button onClick={()=>setOpen(open === index ? null : index)} aria-expanded={open === index} aria-controls={`faq-${index}`}><span>0{index+1}</span><strong>{question}</strong><b aria-hidden="true">{open === index ? '-' : '+'}</b></button><div id={`faq-${index}`} hidden={open !== index}><p>{answer}</p></div></div>)}</div></section></>; }
