'use client';

import { useState } from 'react';
import { FlowDiagram } from '@/components/enrichment/CapabilityVisuals';
import { Button, PageHero, SectionHeader } from '@/components/ui/Primitives';

const capabilityNames = ['Intelligent Systems', 'Intelligent Infrastructure', 'Custom Models', 'Custom Infrastructure', 'AI R&D', 'Consulting & Advisory'];
const faq = [
  ['What is GenJecX?', 'GenJecX is an AI R&D studio building intelligent systems, infrastructure, custom models and research-led AI solutions.'],
  ['Are you an AI consultancy?', 'Not primarily. Technical advisory is available when judgment is needed, but the core work is building and researching systems.'],
  ['Do you only work with startups?', 'No. We work with startups, product companies, technology teams, founders and organizations facing technically meaningful AI problems.'],
  ['Do you build AI agents?', 'Yes, when agents are actually appropriate to the problem.'],
  ['Do you build custom models?', 'Yes — but only when existing models cannot reasonably satisfy the requirement.'],
  ['Can you work with an existing AI product?', 'Yes. Existing systems can be audited, rearchitected, improved or extended.'],
  ['Can you work with our existing infrastructure?', 'Yes. Integration is designed around the environment already in place.'],
  ['Do you replace existing systems?', 'Not automatically. The goal is to improve the system, not replace technology simply because we did not build it.'],
  ['Do you work with confidential data?', 'Projects can be structured around appropriate security, access, deployment and data-handling requirements.'],
  ['How do projects start?', 'Usually with a conversation or technical assessment. Explaining the problem is enough to begin.'],
  ['How long does a project take?', 'It depends on depth. Focused AI solutions can be relatively short engagements; custom intelligence systems and R&D require more involved engineering.'],
  ['How do you decide what to build?', 'By evaluating the problem, data, model requirements, system architecture, constraints and expected outcome.'],
  ['Do you provide ongoing support?', 'Depending on the system, this can include maintenance, evaluation, optimization, infrastructure support and continued R&D.'],
];

export function AboutExperience() {
  return <><PageHero kicker="About GenJecX" title={<>An AI R&amp;D studio for systems that <em>keep becoming more useful.</em></>} copy="GenJecX works with companies that need more than a surface-level AI feature. We build the intelligence, infrastructure, models and technical foundations underneath those features."><div className="gx-page-actions"><Button href="/products">What we build</Button><Button href="/ArchitectureAudit" variant="secondary">Discuss your system</Button></div></PageHero><section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">What we believe</div><h2 className="gx-display">AI is becoming <em>infrastructure.</em></h2></div><div className="gx-copy"><p>The opportunity is not simply adding AI to software. It is building software that becomes meaningfully more capable because intelligence is designed into the system.</p><p>We work across knowledge, retrieval, agents, models, infrastructure, evaluation and research.</p></div></div></section><section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="What we build" title={<>We build the system, not just the <em>feature.</em></>} /><div className="gx-about-principles">{capabilityNames.map((title,index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>Designed around the problem, its operating environment and the system&apos;s ability to improve over time.</p></article>)}</div><FlowDiagram label="GenJecX philosophy" steps={['Research', 'Architecture', 'Engineering', 'Evaluation', 'Intelligence']} /></div></section><section className="gx-section"><div className="gx-container"><SectionHeader kicker="Founder-led" title={<>Garima Kalra — Founder, <em>GenJecX.</em></>} copy="Founder-led R&D studio focused on turning ambiguous AI problems into working technical systems."/><p className="gx-principle-statement">We research when the answer isn&apos;t obvious. We evaluate instead of assuming. We design for iteration. We care about what happens after the demo.</p></div></section></>;
}

const careerValues = [['Curiosity','Understand why something works, not just make it work once.'],['Ownership','Move an ambiguous problem toward a real answer.'],['High Standards','Care about architecture, reliability, clarity and details.'],['Research Mindset','Test assumptions and change your mind when evidence says so.'],['System Thinking','Understand that the model is only one layer of the system.'],['Long-Term Default','Build things that can survive their first successful demo.'],['Generous With Rigor','Challenge ideas without making the room worse for everyone.']];
export function CareersExperience() {
  return <><PageHero kicker="Careers" title={<>Build the systems that <em>matter next.</em></>} copy="We&apos;re interested in people who are curious about intelligence, rigorous about systems and willing to think beyond the next short-term milestone."><div className="gx-page-actions"><Button href="mailto:genjecx@gmail.com">Introduce yourself</Button><Button href="/about" variant="secondary">About GenJecX</Button></div></PageHero><section className="gx-section"><div className="gx-container"><SectionHeader kicker="How we think about the work" title={<>Curiosity, ownership and <em>high standards.</em></>} /><div className="gx-careers-values">{careerValues.map(([title,copy])=><article key={title}><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="gx-section gx-soft-band"><div className="gx-container gx-two-column"><div><div className="gx-kicker">What working here looks like</div><h2 className="gx-display">That&apos;s part of the <em>work.</em></h2></div><div className="gx-copy"><p>One day may involve debugging an agent, designing retrieval, researching a model architecture, reviewing infrastructure, writing an evaluation harness or questioning whether the whole approach is wrong.</p><p>Roles of interest include AI / ML Engineers, Full-Stack AI Engineers, Research Engineers, Systems Engineers and interns across AI engineering or research. No specific vacancy is claimed.</p></div></div></section></>;
}

const roadmap = [['Stronger Intelligent Systems','Better agents, workflows, memory and decision systems.'],['Deeper Intelligence Infrastructure','Better knowledge routing, evaluation, observability and persistent intelligence.'],['Model Research','Specialized models and architectures where generic capability reaches its limits.'],['Research Infrastructure','Tools for experimentation, training, inference and evaluation.'],['Reusable System Knowledge','Turning validated architectures and experiments into reusable patterns.'],['Applied R&D','Exploring specialized intelligence domains without promising unsupported outcomes.']];
export function RoadmapExperience() { return <><PageHero kicker="Roadmap" title={<>A direction of <em>travel.</em></>} copy="Not a list of empty promises. GenJecX&apos;s roadmap is organized around stronger systems, deeper research and more durable intelligence infrastructure."/><section className="gx-section"><div className="gx-container"><FlowDiagram label="Direction map" steps={['Now', 'Explore', 'Validate', 'Build', 'Generalize']} /><div className="gx-roadmap-full">{roadmap.map(([stage,copy],index)=><article key={stage}><span>0{index+1}</span><h2 className="gx-display">{stage}</h2><p>{copy}</p></article>)}</div><p className="gx-principle-statement">We don&apos;t publish dates simply to make the roadmap look busy. We publish direction when there is something meaningful behind it.</p></div></section></>; }

export function FAQExperience() { const [open,setOpen] = useState<number | null>(0); return <><PageHero kicker="FAQ" title={<>Clear answers before the <em>next decision.</em></>} copy="A practical introduction to how GenJecX thinks about intelligent systems, architecture and long-term technical work."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Discuss your system</Button><Button href="/docs" variant="secondary">Explore Docs</Button></div></PageHero><section className="gx-section"><div className="gx-container gx-faq-wrap">{faq.map(([question,answer],index)=><div className="gx-faq-item" key={question}><button onClick={()=>setOpen(open === index ? null : index)} aria-expanded={open === index} aria-controls={`faq-${index}`}><span>0{index+1}</span><strong>{question}</strong><b aria-hidden="true">{open === index ? '-' : '+'}</b></button><div id={`faq-${index}`} hidden={open !== index}><p>{answer}</p></div></div>)}</div></section></>; }
