'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Button, PageHero, SectionHeader } from '@/components/ui/Primitives';

const principles = [
  ['Research before scale', 'We move deliberately enough to understand the system we are building and the consequences of its decisions.'],
  ['Problems come first', 'Tools are secondary. The work begins by understanding the underlying problem and the context around it.'],
  ['Depth over speed', 'We choose capability and a durable foundation over a quick, disconnected deployment.'],
  ['Intellectual honesty', 'Constraints, failures and uncertainty are part of serious technical work—not something to hide.'],
];

export function AboutExperience() { return <>
  <PageHero kicker="About Genjecx" title={<>An AI R&D studio for systems that <em>keep becoming more useful.</em></>} copy="Genjecx works with companies that need more than a surface-level AI feature: intelligent systems, the infrastructure beneath them and the judgment to build them well."><div className="gx-page-actions"><Button href="/products">What we build</Button><Button href="/ArchitectureAudit" variant="secondary">Start a conversation</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container gx-two-column"><div><div className="gx-kicker">Who we are</div><h2 className="gx-display">Technical depth with a <em>human point of view.</em></h2></div><div className="gx-copy"><p>Genjecx is built around long-term intelligence infrastructure: systems that use data, knowledge, models, agents and feedback as one evolving whole.</p><p>We can help clarify what should be built, shape its architecture, implement it and continue to evolve it when the work warrants a long-term partner.</p></div></div></section>
  <section className="gx-section gx-soft-band"><div className="gx-container"><SectionHeader kicker="What guides the work" title={<>The principles behind every <em>technical decision.</em></>} /><div className="gx-about-principles">{principles.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="The people behind the work" title={<>Built by people who care about <em>how systems think.</em></>} copy="Our existing team information remains available as a legacy-compatible page while this About experience provides the wider Genjecx narrative."/><div className="gx-people-link"><Link href="/Founders">Meet the founders and their areas of focus →</Link></div></div></section>
  <section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Build with Genjecx</div><h2 className="gx-display">The system beneath the idea matters.</h2><p>Let’s discuss what intelligence should look like in your company.</p><Button href="/ArchitectureAudit">Start a conversation</Button></div></section>
</>; }

export function CareersExperience() { return <>
  <PageHero kicker="Careers" title={<>Build the systems that <em>matter next.</em></>} copy="Genjecx is interested in people who are curious about intelligence, rigorous about systems and willing to think beyond the next short-term milestone."><div className="gx-page-actions"><Button href="mailto:genjecx@gmail.com">Introduce yourself</Button><Button href="/about" variant="secondary">About Genjecx</Button></div></PageHero>
  <section className="gx-section"><div className="gx-container"><SectionHeader kicker="How we think about the work" title={<>Curiosity, ownership and <em>high standards.</em></>} copy="This is not a list of open roles or promised benefits. It is the kind of working environment Genjecx is intentionally building as the right opportunities arise."/><div className="gx-careers-values">{[['Research minded','You enjoy asking the deeper question before reaching for a familiar answer.'],['Systems oriented','You see how data, models, interfaces and people affect one another.'],['Long-term by default','You value foundations that can be understood, maintained and improved.'],['Generous with rigor','You care about clear thinking, honest feedback and work that holds up.']].map(([title,copy])=><article key={title}><h3 className="gx-display">{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="gx-section gx-process-band"><div className="gx-container gx-resource-note"><div className="gx-kicker">No fabricated vacancies</div><h2 className="gx-display">Interested in the work?</h2><p>No specific open roles are published in the current production content. If your experience aligns with research, engineering or intelligent systems, you can share a thoughtful introduction.</p><Button href="mailto:genjecx@gmail.com">Contact Genjecx</Button></div></section>
</>; }

const roadmap = [['Now','Building the foundation for intelligent systems and the work that makes them durable.'],['Next','Deepening research-led capabilities, technical knowledge and reusable system patterns.'],['Later','Expanding the ways Genjecx can help companies own and evolve their intelligence layers.'],['Beyond','Exploring the opportunities that emerge as systems, research and real-world feedback compound.']];
export function RoadmapExperience() { return <>
  <PageHero kicker="Roadmap" title={<>A direction of travel, not a list of <em>empty promises.</em></>} copy="Genjecx’s roadmap is organized around stronger systems, deeper research and more durable intelligence infrastructure—not unsupported dates or product announcements."/><section className="gx-section"><div className="gx-container"><SectionHeader kicker="Direction" title={<>What we are continuing to <em>develop.</em></>} /><div className="gx-roadmap-full">{roadmap.map(([stage,copy],index)=><article key={stage}><span>0{index+1}</span><h2 className="gx-display">{stage}</h2><p>{copy}</p></article>)}</div></div></section><section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Build now</div><h2 className="gx-display">Your system does not need to wait for the roadmap.</h2><p>Start with the intelligence challenge in front of you.</p><Button href="/ArchitectureAudit">Start a conversation</Button></div></section></>; }

const questions = [
  ['What is Genjecx?', 'Genjecx is an AI R&D studio that helps companies design intelligent systems and the infrastructure beneath them.'],
  ['What does an AI R&D studio do?', 'The work can span technical strategy, intelligent workflows, data and knowledge systems, architecture, research and custom development—depending on what the problem genuinely needs.'],
  ['Do we need to know exactly what to build?', 'No. An architecture audit or advisory conversation is designed to clarify the opportunity, constraints and a sensible next decision before a larger build begins.'],
  ['Can Genjecx work with our existing technology?', 'The approach is designed around the environment a company already has: its data, workflows, infrastructure, interfaces and operational constraints.'],
  ['Does Genjecx only use custom models?', 'No. Custom model work is appropriate only when the problem justifies it. The goal is the right architecture, not custom development for its own sake.'],
  ['What does ownership mean?', 'It means making intentional decisions about the intelligence layer your company needs to understand, control and extend over time.'],
  ['How do engagements begin?', 'Most begin with a conversation about the problem and the current environment. Architecture audits are available when a structured technical assessment is the appropriate next step.'],
];
export function FAQExperience() { const [open,setOpen] = useState<number | null>(0); return <><PageHero kicker="FAQ" title={<>Clear answers before the <em>next decision.</em></>} copy="A practical introduction to how Genjecx thinks about intelligent systems, architecture and long-term technical work."><div className="gx-page-actions"><Button href="/ArchitectureAudit">Discuss your situation</Button><Button href="/docs" variant="secondary">Explore Docs</Button></div></PageHero><section className="gx-section"><div className="gx-container gx-faq-wrap">{questions.map(([question,answer],index)=><div className="gx-faq-item" key={question}><button onClick={()=>setOpen(open === index ? null : index)} aria-expanded={open === index} aria-controls={`faq-${index}`}><span>0{index+1}</span><strong>{question}</strong><b>{open === index ? '−' : '+'}</b></button><div id={`faq-${index}`} hidden={open !== index}><p>{answer}</p></div></div>)}</div></section><section className="gx-marketing-cta"><div className="gx-container"><div className="gx-kicker">Still unclear?</div><h2 className="gx-display">The right question is a good place to begin.</h2><p>Tell us what you are trying to understand or build.</p><Button href="/ArchitectureAudit">Start a conversation</Button></div></section></>; }
